# Site settings
title: Phil Sturgeon
email: me@philsturgeon.uk
description: > # this means to ignore newlines until "baseurl:"
  I'm the ex-founder of PyroCMS, Senior Developer at Ride, a voting PHP-FIG member, and occasionally I get chased by bears
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://philsturgeon.uk" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
highlighter: pygments
paginate: 8
exclude: ["Gemfile", "Gemfile.lock"]

# Content Settings
logo: "/assets/images/logo.jpg"
cover: "/assets/images/ciderphpants.jpg"

author: 'Phil Sturgeon'
author_image: "/assets/images/author.jpg"
author_bio: "Phil has contributed to CodeIgniter, FuelPHP, Laravel and handfuls of other projects, to try and make the PHP community a better place."

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/philsturgeon
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/philsturgeon
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
