# Site settings
title: Phil Sturgeon
email: me@philsturgeon.uk
description: > # this means to ignore newlines until "baseurl:"
  I'm the ex-founder of PyroCMS, Senior Developer at Ride, a voting PHP-FIG member, and occasionally I get chased by bears
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://philsturgeon.uk" # the base hostname & protocol for your site
twitter_username: philsturgeon
github_username:  philsturgeon

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 8
exclude: ["Gemfile", "Gemfile.lock"]
